name: ENV Variables

on: push

env:
  WF_ENV: Available to All jobs

jobs:
  log_env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log_env job

    steps:
      - name: Log Env Variable
        env:
          STEP_ENV: Available to Only This step
        run: |
          echo "Env Variable: ${WF_ENV}"
          echo "Job Variable: ${JOB_ENV}"
          echo "Step Variable: ${STEP_ENV}"

  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default Env Variables
        run: |
          echo "Home : ${HOME}"
          echo "Github Workflow : ${GITHUB_WORKFLOW}"
          echo "Github Action : ${GITHUB_ACTION}"
          echo "Github Actions : ${GITHUB_ACTIONS}"
